### ISSUE TITLE
bids rc4 pdf unreadable with mac preview or acrobat

### ISSUE THREAD

**Issue by mrjeffs** [INCF/BIDS#2]

**Comment by mrjeffs** [comment]
well download raw works. tho not intuitive.

**Comment by chrisfilo** [comment]
You mean the github preview does not work? https://github.com/INCF/BIDS/blob/gh-pages/bids_spec1.0.0-rc4.pdf 

Or the pdf on the website? http://bids.neuroimaging.io/bids_spec1.0.0-rc4.pdf

**Comment by mrjeffs** [comment]
Hi chris. The web display works. It's the saving file to disk that is not a recognizable pdf format. J

Get Outlook<https://aka.ms/uzin6x>




On Wed, May 4, 2016 at 3:35 PM -0700, "Chris Filo Gorgolewski" <notifications@github.com<mailto:notifications@github.com>> wrote:


You mean the github preview does not work? https://github.com/INCF/BIDS/blob/gh-pages/bids_spec1.0.0-rc4.pdf

Or the pdf on the website? http://bids.neuroimaging.io/bids_spec1.0.0-rc4.pdf

-

**Comment by chrisfilo** [comment]
So you save this file http://bids.neuroimaging.io/bids_spec1.0.0-rc4.pdf (not this one https://github.com/INCF/BIDS/blob/gh-pages/bids_spec1.0.0-rc4.pdf) to your hard drive try to open it in acrobat reader and it does not work?
