### ISSUE TITLE
several links non-functional and/or outdated

### ISSUE THREAD

**Issue by sappelhoff** [INCF/BIDS#23]
Using the most recent Firefox browser, several links on [bids.neuroimaging.io](http://bids.neuroimaging.io) do not work as expected. Nothing happens when clicked upon - only through right-click "open in new tab", the links do work.

This is True for e.g., 
![screenshot from 2018-05-25 09-13-39](https://user-images.githubusercontent.com/9084751/40531211-f627d814-5ffb-11e8-9d1d-615512cc56c4.png)

... but also for
![screenshot from 2018-05-25 09-17-23](https://user-images.githubusercontent.com/9084751/40531364-7a34c91e-5ffc-11e8-9847-4dbb592e7295.png)

(Which are arguably the two most important links?)

Lastly, one would expect that [http://bids.neuroimaging.io/bids_spec.pdf](http://bids.neuroimaging.io/bids_spec.pdf) would link to the most recent BIDS version, which at this point it does not.

**Comment by chrisfilo** [comment]
Thanks for reporting. Do you have any plugins/extensions blocking JavaScript enabled?

**Comment by sappelhoff** [comment]
Yes, and when switching them off everything works ... uups. Sorry for not checking that beforehand. However, it's still confusing that with the plugins enabled some links (e.g., PET-Extension, directly below BIDS DRAFT) do still work and others don't. Any idea why?

> Lastly, one would expect that http://bids.neuroimaging.io/bids_spec.pdf would link to the most recent BIDS version, which at this point it does not.

Is still valid I guess.

**Comment by chrisfilo** [comment]
We are tracking those links to learn how people are using the website. This way I can tell you that 13.2% of visitors are looking at the specification.

As for http://bids.neuroimaging.io/bids_spec.pdf - is this a broken link from an external site?

**Comment by sappelhoff** [comment]
Ahhh okay :-) ... so not really an issue one could solve once people try to block such tracking.

I had used http://bids.neuroimaging.io/bids_spec.pdf  some time ago while documenting an internal project and was just re-checking the link today. Do you disagree with the reasoning that the blank link should link to the most recent version ... and all other versions should get a link such as `[...]1.0.2.pdf` (as is already the case now)?

**Comment by chrisfilo** [comment]
Ah - yes got it. Will fix it now.
