### ISSUE TITLE
Add contributors guide to the website

### ISSUE THREAD

**Issue by chrisfilo** [INCF/BIDS#3]
Source https://docs.google.com/document/d/1pWmEEY-1-WuwBPNy5tDAxVJYQ9Een4hZJM06tQZg8X4/edit?disco=AAAABQ0U5J8&ts=59dba09b

**Comment by chrisfilo** [comment]
This guide would describe various ways one can contribute to the BIDS ecosystem and how to best do it.

**Comment by SetCodesToFire** [comment]
Can I contribute in this? @chrisfilo

**Comment by chrisfilo** [comment]
Sorry this has already been fixed by #17
